version: 2.1

jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Build
          command: ./gradlew clean --warning-mode=all build
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  test_module_app:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint app:test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports

  test_module_favorite:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint favorite:test
      - store_test_results:
          path: favorite/build/test-results
      - store_artifacts:
          path: favorite/build/reports
          destination: reports

  test_module_core:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint core:test
      - store_test_results:
          path: core/build/test-results
      - store_artifacts:
          path: core/build/reports
          destination: reports

  code_coverage_module_app:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Unit Test Coverage
          command: ./gradlew clean --warning-mode=all app:testDebugUnitTestCoverage
      - store_artifacts:
          path: app/build/app-reports/testDebugUnitTestCoverage/html
          destination: coverage

  code_coverage_module_favorite:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Unit Test Coverage
          command: ./gradlew clean --warning-mode=all favorite:testDebugUnitTestCoverage
      - store_artifacts:
          path: favorite/build/favorite-reports/testDebugUnitTestCoverage/html
          destination: coverage

  code_coverage_module_core:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android
            - ~/android
            - ~/.m2
            - ~/.gradle
      - run:
          name: Unit Test Coverage
          command: ./gradlew clean --warning-mode=all core:testDebugUnitTestCoverage
      - store_artifacts:
          path: core/build/core-reports/testDebugUnitTestCoverage/html
          destination: coverage

workflows:
  build | test | code_coverage:
    jobs:
      - build
      - test_module_app
      - test_module_favorite
      - test_module_core
      - code_coverage_module_app
      - code_coverage_module_favorite
      - code_coverage_module_core