version: 2.1

jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
#      - run:
#          name: create avd
#          command: |
#            SYSTEM_IMAGES="system-images;android-30;google_apis;x86_64"
#            sdkmanager "$SYSTEM_IMAGES"
#            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
#
#      - run:
#          name: launch emulator
#          command: |
#            emulator -avd test -delay-adb -verbose -no-window -noaudio -no-boot-anim -memory 4096 -accel on
#          background: true
#      - run:
#          name: wait for emulator to start
#          command: circle-android wait-for-boot
#
#      - run:
#          name: disable emulator animations
#          command: |
#            adb shell settings put global window_animation_scale 0.0
#            adb shell settings put global transition_animation_scale 0.0
#            adb shell settings put global animator_duration_scale 0.0
#
#      - run:
#          name: gradle connected android test
#          command: |
#            MAX_TRIES=2
#            run_with_retry() {
#               n=1
#               until [ $n -gt $MAX_TRIES ]
#               do
#                  echo "Starting test attempt $n"
#                  ./gradlew connectedAndroidTest && break
#                  n=$[$n+1]
#                  sleep 5
#               done
#               if [ $n -gt $MAX_TRIES ]; then
#                 echo "Max tries reached ($MAX_TRIES)"
#                 exit 1
#               fi
#            }
#            run_with_retry
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Build
          command: ./gradlew clean --warning-mode=all build
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  test_module_app:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint app:test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports

  test_module_favorite:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint favorite:test
      - store_test_results:
          path: favorite/build/test-results
      - store_artifacts:
          path: favorite/build/reports
          destination: reports

  test_module_core:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Run Tests
          command: ./gradlew clean --warning-mode=all lint core:test
      - store_test_results:
          path: core/build/test-results
      - store_artifacts:
          path: core/build/reports
          destination: reports

  code_coverage_module_app:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Unit Test Coverage
          command: ./gradlew clean --warning-mode=all app:testDebugUnitTestCoverage
      - store_artifacts:
          path: app/build/app-reports/testDebugUnitTestCoverage/html
          destination: coverage

  code_coverage_module_favorite:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Unit Test Coverage
          command: ./gradlew clean --warning-mode=all favorite:testDebugUnitTestCoverage
      - store_artifacts:
          path: favorite/build/favorite-reports/testDebugUnitTestCoverage/html
          destination: coverage

  code_coverage_module_core:
    machine:
      image: android:202102-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: replace gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean --warning-mode=all androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.m2
            - ~/.gradle
      - run:
          name: Unit Test Coverage
          command: ./gradlew clean --warning-mode=all core:testDebugUnitTestCoverage
      - store_artifacts:
          path: core/build/core-reports/testDebugUnitTestCoverage/html
          destination: coverage

workflows:
  build | test | code_coverage:
    jobs:
      - build
      - test_module_app
      - test_module_favorite
      - test_module_core
      - code_coverage_module_app
      - code_coverage_module_favorite
      - code_coverage_module_core